### ISSUE TITLE
Error while training on one-class dataset

### ISSUE THREAD

**Issue by Youcunl** [youngwanLEE/centermask2#1]
Thanks for your great work.
When I am training the model on my own dataset which has only one class(i.e. person), I got the error:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/detectron2_repo/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/liuyoucun/human_segmentation/centermask2-master/train_net.py", line 234, in main
    return trainer.train()
  File "/home/liuyoucun/human_segmentation/centermask2-master/train_net.py", line 113, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/home/liuyoucun/human_segmentation/centermask2-master/train_net.py", line 102, in train_loop
    self.run_step()
  File "/detectron2_repo/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/detectron2_repo/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liuyoucun/human_segmentation/centermask2-master/centermask/modeling/centermask/center_heads.py", line 321, in forward
    losses, mask_features, selected_mask, labels, maskiou_targets = self._forward_mask(features_list, proposals)
  File "/home/liuyoucun/human_segmentation/centermask2-master/centermask/modeling/centermask/center_heads.py", line 387, in _forward_mask
    loss, selected_mask, labels, maskiou_targets = mask_rcnn_loss(mask_logits, proposals, self.maskiou_on)
  File "/home/liuyoucun/human_segmentation/centermask2-master/centermask/modeling/centermask/mask_head.py", line 97, in mask_rcnn_loss
    gt_classes = cat(gt_classes, dim=0)
  File "/detectron2_repo/detectron2/layers/wrappers.py", line 25, in cat
    return torch.cat(tensors, dim)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]

I suppose there is bug at line 63 in mask_head.py:
`cls_agnostic_mask = pred_mask_logits.size(1) == 1`
it will treat one-class-specific mask as class-agnostic mask then skip the code at line 76-78:

<img width="589" alt="截圖 2020-02-21 下午9 19 10" src="https://user-images.githubusercontent.com/15208467/75037732-cf4bf500-54ef-11ea-90ec-d776a717a1a5.png">

and finally leads to the torch.cat RuntimeError.

However, setting cls_agnostic_mask to false makes the code work.

**Comment by AlexFridman** [comment]
Hello, @Youcunl! I'm trying to run it on a single class too. I've applied your modification, but I'm getting the following error:
```
Traceback (most recent call last):
  File "train_net.py", line 350, in <module>
    args=(args,),
  File "/home/alfrid/.virtualenvs/jupyter/lib/python3.6/site-packages/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "train_net.py", line 338, in main
    return trainer.train()
  File "train_net.py", line 201, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "train_net.py", line 190, in train_loop
    self.run_step()
  File "/home/alfrid/.virtualenvs/jupyter/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 233, in run_step
    self.optimizer.step()
  File "/home/alfrid/.virtualenvs/jupyter/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 66, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/alfrid/.virtualenvs/jupyter/lib/python3.6/site-packages/torch/optim/sgd.py", line 106, in step
    p.data.add_(-group['lr'], d_p)
RuntimeError: output with shape [1, 256, 3, 3] doesn't match the broadcast shape [80, 256, 3, 3]
```

Here is settings I've changed:
```
    cfg.MODEL.WEIGHTS = '/home/alfrid/Downloads/centermask2-V-99-eSE-FPN-ms-3x.pth'
    # cfg.MODEL.WEIGHTS = '/home/alfrid/Downloads/centermask2-V-57-eSE-FPN-ms-3x.pth'
    cfg.DATASETS.TRAIN = tuple(DATASETS)
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1
    cfg.MODEL.FCOS.NUM_CLASSES = 1
    cfg.MODEL.RETINANET.NUM_CLASSES = 1
    cfg.OUTPUT_DIR = OUTPUT_DIR
    cfg.SOLVER.CHECKPOINT_PERIOD = 5000
    cfg.SOLVER.IMS_PER_BATCH = 2
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
    cfg.DATALOADER.NUM_WORKERS = 2
    cfg.SOLVER.MAX_ITER = 1250000
    # cfg.VIS_PERIOD = 1000
    cfg.TEST.DETECTIONS_PER_IMAGE = 500
```

It looks like it still trying to work on 80 classes. Could you please share how did you manage to run it?

**Comment by youngwanLEE** [comment]
The section you point out is from detectron2 and I didn't touch that part. 

How about asking to detectron2 team?

**Comment by Youcunl** [comment]
@youngwanLEE, actually, this section I pointed out is at centermask/modeling/centermask/mask_head.py not at detectron2 repo.
Anyway, I would open an issue in detectron2 repo

**Comment by youngwanLEE** [comment]
@Youcunl 
I mean I create mask_head.py based on detectron2 code by modifying the origin mask_head from detetectron2.

**Comment by youngwanLEE** [comment]
@Youcunl 
Did you solve the problem?

**Comment by youngwanLEE** [comment]
@Youcunl 

I modified the code.

Now you can pull the code and try it again.
