### ISSUE TITLE
Error about use pretrainde weight to train one-class dataset?

### ISSUE THREAD

**Issue by EasonEdison** [youngwanLEE/centermask2#14]
I want to use this weight to finetune my dataset, I use 2 gpus.
The weight I use is ```centermask-V2-99-FPN-ms-3x.pth```
What I change is as follow:
1. In ```centermask_V_99_eSE_FPN_ms_3x.yaml``` change ```MAX_ITER=300000```,and change ```MODEL.WEIGHT``` to path of  ```centermask-V2-99-FPN-ms-3x.pth```
2. In ```Base-CenterMask-VoVNet.yaml``` change ```IMS_PER_BATCH: 2```, ```BASE_LR: 0.002```
3. register my dataset, my dataset only has one class, and  annotation ```from .dataset_mapper import DatasetMapperWithBasis``` because it get error
4. In ```defaults.py``` change ```_C.MODEL.FCOS.NUM_CLASSES = 1```
Then I run ```train_net.py```, it show:
```
Traceback (most recent call last):
  File "/home/ql-b423/Desktop/TXH/CenterMask/new/centermask2/train_net.py", line 233, in <module>
    args=(args,),
  File "/home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/ql-b423/Desktop/TXH/CenterMask/new/centermask2/train_net.py", line 218, in main
    return trainer.train()
  File "/home/ql-b423/Desktop/TXH/CenterMask/new/centermask2/train_net.py", line 97, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/home/ql-b423/Desktop/TXH/CenterMask/new/centermask2/train_net.py", line 86, in train_loop
    self.run_step()
  File "/home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 234, in run_step
    self.optimizer.step()
  File "/home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 66, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/optim/sgd.py", line 100, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: The size of tensor a (3) must match the size of tensor b (512) at non-singleton dimension 1


Process finished with exit code 1
```
Could you tell me what am I doing wrong?

**Comment by youngwanLEE** [comment]
I didn't see your errors when I tried to train on one-class dataset.

I'm supposed to update our code for one-class dataset.

Anyway, I recommend increasing `IMS_PER_BATCH`.

**Comment by youngwanLEE** [comment]
@EasonEdison 

I modified the code for one-class dataset.

Try it again and open this issue if the problem occurs again.
