### ISSUE TITLE
Assertion error while running demo.py

### ISSUE THREAD

**Issue by AnjuMKaimal** [youngwanLEE/centermask2#15]
(torchtest) C:\Users\User\Downloads\centermask2\demo>python demo.py
[32m[03/11 10:18:37 detectron2]: [0mArguments: Namespace(confidence_threshold=0.5, config_file='C:/Users/User/Downloads/centermask2/demo/detectron2/configs/quick_schedules/fast_rcnn_R_50_FPN_inference_acc_test.yaml', input='C:/Users/User/Downloads/CenterMask-master/demo/images', opts=[], output='C:/Users/User/Downloads/centermask2/output', video_input=None, webcam=False)
  0%|                                                                                          | 0/134 [00:00<?, ?it/s]Process _PredictWorker-1:
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\torchtest\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\User\Downloads\centermask2\demo\predictor.py", line 179, in run
    result = predictor(data)
  File "C:\Users\User\Anaconda3\envs\torchtest\lib\site-packages\detectron2-0.1.1-py3.7-win-amd64.egg\detectron2\engine\defaults.py", line 196, in __call__
    predictions = self.model([inputs])[0]
  File "C:\Users\User\Anaconda3\envs\torchtest\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\User\Anaconda3\envs\torchtest\lib\site-packages\detectron2-0.1.1-py3.7-win-amd64.egg\detectron2\modeling\meta_arch\rcnn.py", line 108, in forward
    return self.inference(batched_inputs)
  File "C:\Users\User\Anaconda3\envs\torchtest\lib\site-packages\detectron2-0.1.1-py3.7-win-amd64.egg\detectron2\modeling\meta_arch\rcnn.py", line 167, in inference
    assert "proposals" in batched_inputs[0]
AssertionError

**Comment by youngwanLEE** [comment]
Did you try using centermask config and model weight?

**Comment by youngwanLEE** [comment]
@AnjuMKaimal 

I close this issue because you are no longer responding.

If you have another issue, then re-open this issue.
