### ISSUE TITLE
Getting error during training

### ISSUE THREAD

**Issue by batrlatom** [youngwanLEE/centermask2#32]
Hi, 
I am getting error in mask_head.py .   According the stacktrace,  this line make a problem  mask_ratios = torch.max(mask_ratios, value_eps)

Error is:
RuntimeError: Expected object of scalar type double but got scalar type float for argument 'other'

Could you please take a look at it? 

The only thing I changed is registering my own dataset for training:

```

def setup(args):
    """
    Create configs and perform basic setups.
    """
    cfg = get_cfg()
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)


    from detectron2.data.datasets import register_coco_instances

    register_coco_instances("bad", {}, "datasets/coco/annotations/instances_train2017.json",
                            "datasets/coco/annotations/images")

    cfg.DATASETS.TRAIN = ("bad",)

    cfg.SOLVER.IMS_PER_BATCH = 8
    cfg.SOLVER.BASE_LR = 0.001
    cfg.SOLVER.MAX_ITER = 2000
    cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
    cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1


    cfg.freeze()
    default_setup(cfg, args)
    return cfg

```

###########################################

/opt/conda/conda-bld/pytorch_1587428266983/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)
Traceback (most recent call last):
  File "/home/tom/PycharmProjects/centermask2/train_net.py", line 247, in <module>
    args=(args,),
  File "/home/tom/miniconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/engine/launch.py", line 57, in launch
    main_func(*args)
  File "/home/tom/PycharmProjects/centermask2/train_net.py", line 235, in main
    return trainer.train()
  File "/home/tom/PycharmProjects/centermask2/train_net.py", line 97, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/home/tom/PycharmProjects/centermask2/train_net.py", line 86, in train_loop
    self.run_step()
  File "/home/tom/miniconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File "/home/tom/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tom/miniconda3/envs/detectron2/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/tom/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tom/PycharmProjects/centermask2/centermask/modeling/centermask/center_heads.py", line 401, in forward
    losses, mask_features, selected_mask, labels, maskiou_targets = self._forward_mask(features, proposals)
  File "/home/tom/PycharmProjects/centermask2/centermask/modeling/centermask/center_heads.py", line 476, in _forward_mask
    loss, selected_mask, labels, maskiou_targets = mask_rcnn_loss(mask_logits, proposals, self.maskiou_on)
  File "/home/tom/PycharmProjects/centermask2/centermask/modeling/centermask/mask_head.py", line 153, in mask_rcnn_loss
    mask_ratios = torch.max(mask_ratios, value_eps)
RuntimeError: Expected object of scalar type double but got scalar type float for argument 'other'

**Comment by SkeletonOne** [comment]
Have you solved it? I meet the same problem.

**Comment by SkeletonOne** [comment]
I have figured it out. The thing is for the inputs of `torch.max`, one is float and the other is double.
Solution: In `./centermask/modeling/centermask/mask_head.py`, change
`value_eps = 1e-10 * torch.ones(gt_masks.shape[0], device=gt_masks.device)`
to
`value_eps = 1e-10 * torch.ones(gt_masks.shape[0], device=gt_masks.device).double()`
and also change
`value_1 = torch.ones(pred_masks.shape[0], device=gt_masks.device)`
to
`value_1 = torch.ones(pred_masks.shape[0], device=gt_masks.device).double()`.

**Comment by VladKatsman** [comment]
Now it evokes a new problem.

{'loss_mask': tensor(0.6932, device='cuda:1', grad_fn=<BinaryCrossEntropyWithLogitsBackward>),
 'loss_maskiou': tensor(0.5323, device='cuda:1', dtype=torch.float64, grad_fn=<MulBackward0>),
 'loss_fcos_cls': tensor(1.0558, device='cuda:1', grad_fn=<DivBackward0>),
 'loss_fcos_loc': tensor(0.8615, device='cuda:1', grad_fn=<DivBackward0>),
 'loss_fcos_ctr': tensor(0.5908, device='cuda:1', grad_fn=<DivBackward0>)}

loss_maskiou is of type double now instead of float

next change of line 167 helps
return mask_loss, selected_mask, gt_classes, maskiou_targets.float().detach()

**Comment by youngwanLEE** [comment]
@VladKatsman 

Could you send the PR?

**Comment by ArtificialNotImbecile** [comment]
Is this issue related to pytorch version?  Since with pytorch==1.40, I have to comment `.double()` to make training work.

**Comment by ChristofferEdlund** [comment]
Heads up, this update will only work with pytorch > 1.5 , and will break build with pytorch versions less then that.
